### ISSUE TITLE
Timeline Tribunal de contas

### ISSUE THREAD

**Issue by ZePovinho2022** [bentodaniel/portulemicas-website#1]
02/10/2020: Tribunal de Contas avisa que revisão dos contratos públicos abre a porta à corrupção; 
 https://www.publico.pt/2020/10/02/economia/noticia/tribunal-contas-avisa-revisao-contratos-publicos-abre-porta-corrupcao-1933473

03/10/2020: António Costa aponta porta de saída a presidente do Tribunal de Contas, oposição já lança farpas; 
 https://expresso.pt/politica/2020-10-03-Antonio-Costa-aponta-porta-de-saida-a-presidente-do-Tribunal-de-Contas-oposicao-ja-lanca-farpas

07/10/2020:  
Rui Rio ajudou a escolher sucessor do Tribunal de Contas; 
https://observador.pt/2020/10/07/rui-rio-ajudou-a-escolher-sucessor-do-tribunal-de-contas/?cache_bust=1668157799090

Marcelo apoia mudança no Tribunal de Contas: “Não tive um segundo de dúvida”. 
 https://expresso.pt/politica/2020-10-07-Marcelo-apoia-mudanca-no-Tribunal-de-Contas-Nao-tive-um-segundo-de-duvida
 
05/12/2020: Presidente veta novas regras da contratação pública para utilização de fundos europeus 
https://www.publico.pt/2020/12/05/politica/noticia/presidente-veta-novas-regras-contratacao-publica-utilizacao-fundos-europeus-1941934

**Comment by portulemicas** [comment]
Peço desculpa na demora na resposta.
Agradeço os links. Tenho trabalhado para que seja possível qualquer pessoa possa adicionar notícias diretamente no site.
Deverá estar up agora.
