### ISSUE TITLE
melhorar resiliencia com backups no archive.org / archive.is

### ISSUE THREAD

**Issue by rare-magma** [bentodaniel/portulemicas-website#5]
Este projecto depende de informação alojada em sites de jornais portanto esta vulnerável a que os dados desapareçam caso os jornais eliminem as noticias.
Talvez fosse boa ideia automaticamente guardar snapshots das noticias em sites de arquivo como o archive.org ou archive.is

**Comment by rare-magma** [comment]
exemplo: 
https://sicnoticias.pt/pais/2022-11-11-Medina-investigado-por-ajustes-diretos-de-800-mil-euros-a-escritorio-de-Siza-Vieira-8fee2710

https://archive.ph/ARyPN
https://web.archive.org/web/20220000000000*/https://sicnoticias.pt/pais/2022-11-11-Medina-investigado-por-ajustes-diretos-de-800-mil-euros-a-escritorio-de-Siza-Vieira-8fee2710

**Comment by rare-magma** [comment]
exemplo com memento api:
https://robustlinks.mementoweb.org/api-docs/

**Comment by rare-magma** [comment]
ou soluçao portuguesa:
https://arquivo.pt/services/savepagenow?l=en
docs api:
https://github.com/arquivo/pwa-technologies/wiki/APIs

**Comment by bentodaniel** [comment]
Não me tinha lembrado dessa questão. É, de facto, importante que os sites continuem acessíveis.

Obrigado, será implementado num futuro próximo.


Edit: Funcionalidade implementada
